language: java

# Snapshot deployment to Sonatype Maven repository
# The password is encrypted using "travis encrypt -r echo3/echo3extras SONATYPE_PASSWORD=password"
# and only decrypted and set as environment variable by travis-ci if the build runs in the context of
# the echo3/echo3extras github repository.

env:
  global:
  - SONATYPE_USERNAME=bschmid
  - secure: "WkgVn7wbMe7C1KKAFZrvy2BR2eZZ6Bnv1/BPJFHOI+u172wnFPX5FDyjZQiU9xipocnWfa5MZCCpyKBJrNDnWEVlM75bZG6Xpq+yu3tbZgxyNZ3JLxU6a7m5OJo4XjhBiVbX7b+BmD5qHCO5CTgxZIJbKIz0ToUU+ALLcdVlsS8="

after_success:
- python resource/travis-ci/addServer.py
- ant travis.mvn.snapshot
